/*
 * This file is generated by jOOQ.
 */
package io.insight.jgit.jdbc.jooq;

import org.jooq.impl.CatalogImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org",
        "jOOQ version:3.10.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -529013616;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }
}
