/*
 * This file is generated by jOOQ.
 */
package io.insight.jgit.jdbc.jooq;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;

import io.insight.jgit.jdbc.jooq.tables.GitConfig;
import io.insight.jgit.jdbc.jooq.tables.GitRefs;

/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(value = { "http://www.jooq.org",
        "jOOQ version:3.10.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GIT_CONFIG_PRIMARY = Indexes0.GIT_CONFIG_PRIMARY;

    public static final Index GIT_REFS_PRIMARY = Indexes0.GIT_REFS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GIT_CONFIG_PRIMARY = Internal.createIndex("INDEX_git_config_PRIMARY",
                GitConfig.GIT_CONFIG, new OrderField[] { GitConfig.GIT_CONFIG.REPO }, true);

        public static Index GIT_REFS_PRIMARY = Internal.createIndex("INDEX_git_refs_PRIMARY",
                GitRefs.GIT_REFS, new OrderField[] { GitRefs.GIT_REFS.REPO, GitRefs.GIT_REFS.NAME }, true);
    }
}
