/*
 * This file is generated by jOOQ.
 */
package io.insight.jgit.jdbc.jooq;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;

import io.insight.jgit.jdbc.jooq.tables.GitConfig;
import io.insight.jgit.jdbc.jooq.tables.GitObjects;
import io.insight.jgit.jdbc.jooq.tables.GitRefs;
import io.insight.jgit.jdbc.jooq.tables.records.GitConfigRecord;
import io.insight.jgit.jdbc.jooq.tables.records.GitObjectsRecord;
import io.insight.jgit.jdbc.jooq.tables.records.GitRefsRecord;

/**
 * A class modelling foreign key relationships and constraints of tables of the
 * <code>test</code> schema.
 */
@Generated(value = { "http://www.jooq.org",
        "jOOQ version:3.10.6" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GitConfigRecord> KEY_GIT_CONFIG_PRIMARY = UniqueKeys0.KEY_GIT_CONFIG_PRIMARY;

    public static final UniqueKey<GitRefsRecord> KEY_GIT_REFS_PRIMARY = UniqueKeys0.KEY_GIT_REFS_PRIMARY;

    public static final UniqueKey<GitObjectsRecord> KEY_GIT_OBJECTS_PRIMARY = UniqueKeys0.KEY_GIT_OBJECTS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<GitConfigRecord> KEY_GIT_CONFIG_PRIMARY = Internal.createUniqueKey(
                GitConfig.GIT_CONFIG, "KEY_git_config_PRIMARY", GitConfig.GIT_CONFIG.REPO);

        public static final UniqueKey<GitRefsRecord> KEY_GIT_REFS_PRIMARY = Internal.createUniqueKey(
                GitRefs.GIT_REFS, "KEY_git_refs_PRIMARY", GitRefs.GIT_REFS.REPO, GitRefs.GIT_REFS.NAME);

        public static final UniqueKey<GitObjectsRecord> KEY_GIT_OBJECTS_PRIMARY = Internal.createUniqueKey(
                GitObjects.GIT_OBJECTS, "KEY_git_objects_PRIMARY", GitObjects.GIT_OBJECTS.REPO,
                GitObjects.GIT_OBJECTS.OBJECT_ID);
    }
}
